name: flutter_easy_treeview
description: This widget visualises a tree structure, where a node can be any widget.
version: 1.0.0
homepage: https://github.com/nslog11/flutter_easy_treeview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
